apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-convertor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-convertor
  template:
    metadata:
      labels:
        app: video-convertor
    spec:
      containers:
      - image: okteto/hello-world:python
        name: video-convertor

---

apiVersion: v1
kind: Service
metadata:
  name: video-convertor
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "video-convertor"
    port: 8080
  selector:
    app: video-convertor
